fallback = ''

[matching]
'org.keepassxc.KeePassXC' = ''
'org.qutebrowser.qutebrowser' = ''
'Mattermost' = ''
'tiny' = ''
'ghb' = ''
'org.openscad.openscad' = ''
'org.freecadweb.FreeCAD' = ''
'jetbrains-pycharm' = ''
'jetbrains-clion' = ''
'jetbrains-idea' = ''
'jetbrains-webstorm' = ''
'jetbrains-rubymine' = ''
'imv' = ''
'Skype' = ''
'pavucontrol' = ''
'org.freedesktop.ryuukyu.Helvum' = ''
'org.pwmt.zathura' = ''
'libreoffice-writer' = ''
'libreoffice-startcenter' = ''
'libreoffice-calc' = ''
'libreoffice-impress' = ''
'libreoffice-draw' = ''
'gimp-2.99' = ''
'org.inkscape.Inkscape' = ''
'libreoffice-math' = ''
'libreoffice-base' = ''
'discord' = ''
'deadbeef' = ''
'org.strawberrymusicplayer.strawberry' = ''
'mpv' = ''
'mousepad' = ''
'zoom' = ''
'pcmanfm' = ''
'pcmanfm-qt' = ''
'ranger' = ''
'org.qbittorrent.qBittorrent' = ''
'Google-chrome' = ''
'Chromium' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'Spotify' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/nvim ?\w*/' = ''
'nvim' = ''
'/npm/' = ''
'/node/' = ''
'/yarn/' = ''
'floationg-foot' = ''
'foot' = ''
'/VK Messenger/' = ''
'/Oracle VM VirtualBox Manager/' = ''
'/myw10vm /' = ''
'launcher' = ''
'appimagekit_d2192f48ebc43a9db26e1dfa2bc5097b-Kotatogram_Desktop' = ''
'telegramdesktop' = ''
