[icons]
name = "awesome5"
[icons.overrides]
cpu = "\uf625"

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#002b36"
idle_fg = "#93a1a1"
info_bg = "#2aa198"
info_fg = "#002b36"
good_bg = "#859900"
good_fg = "#002b36"
warning_bg = "#b58900"
warning_fg = "#002b36"
critical_bg = "#dc322f"
critical_fg = "#002b36"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
marquee = false
max_width = 25
dynamic_width = true
on_collapsed_click = "strawberry"
on_click = "strawberry"
interface_name_exclude = [".*kdeconnect.*", "JBL_TUNE205BT"]

[[block]]
block = "sound"
on_click = "pavucontrol"
step_width = 1
device_kind = "sink"

[[block]]
block = "sound"
on_click = "pavucontrol"
format = ""
device_kind = "source"

[[block]]
block = "networkmanager"
on_click = "footclient --app-id=nmtui --title='Network configuration' sh -c 'sleep 0.1; nmtui'"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+", "veth[0-9a-f]", "laplocal*"]
interface_name_include = []
device_format = "{icon}{ap}"

[[block]]
block = "memory"
on_click = "footclient htop" 
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
display_type = "memory"
icons = true
clickable = true
interval = 1
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
on_click = "footclient ytop"
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "keyboard_layout"
driver = "sway"
sway_kb_identifier = "1:1:AT_Translated_Set_2_keyboard"
[block.mappings]
"English (US)" = "🇺🇸"
"Russian (N/A)" = "🇷🇺"


[[block]]
block = "battery"
device = "BAT0"
driver = "sysfs"
format = "{percentage}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

